export default {
  SHOW_LOGIN_FORM_ERROR: "SHOW_LOGIN_FORM_ERROR",
  SHOW_SIGNUP_FORM_ERROR: "SHOW_SIGNUP_FORM_ERROR",
  LOGIN_USER: "LOGIN_USER"
//   CLOSE_LOGIN_MODAL: "CLOSE_LOGIN_MODAL",
//   OPEN_LOGIN_MODAL: "OPEN_LOGIN_MODAL",
//   CLOSE_SIGNUP_MODAL: "CLOSE_SIGNUP_MODAL"
};
