export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const SET_MATCHING_USERS = 'SET_MATCHING_USERS';

export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
export const GETTING_USER_GROUP = 'GETTING_USER_GROUP';
export const CREATE_USER_GROUP = 'CREATE_USER_GROUP';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';

export const GET_GROUP_MESSAGES = 'GET_GROUP_MESSAGES';
export const CREATE_GROUP_MESSAGE = 'CREATE_GROUP_MESSAGE';
